development:
    adapter: postgresql
    database: db/development
    username: postgres
    password: postgres
    host: localhost
    encoding: UTF8

test:
    adapter: postgresql
    database: db/test
    username: postgres
    password: postgres
    host: localhost
    encoding: UTF8

production:
    adapter: postgresql
    database: production
    username: postgres
    password: postgres
    host: localhost
    encoding: UTF8

